name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build 7.4-fpm-alpine docker images
      run: |
        cd 7.4-fpm-alpine
        docker build -t xamarie/phpdocker:7.4-fpm-alpine .
        docker push xamarie/phpdocker:7.4-fpm-alpine
