name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build 7.4-fpm-alpine docker images
      run: |
        cd 7.4-fpm-alpine
        docker build -t xamarie/phpdocker:7.4-fpm-alpine .
        docker login --username=${{ secrets.DOCKER_HUB_USER }} --password=${{ secrets.DOCKER_HUB_PASS }} docker.io
        docker push xamarie/phpdocker:7.4-fpm-alpine
    - uses: actions/checkout@master
    - name: Build 7.4-fpm docker images
      run: |
        cd 7.4-fpm
        docker build -t xamarie/phpdocker:7.4-fpm .
        docker login --username=${{ secrets.DOCKER_HUB_USER }} --password=${{ secrets.DOCKER_HUB_PASS }} docker.io
        docker push xamarie/phpdocker:7.4-fpm
